export const nationwidegame = {
  megamillions: {
    name: "MegaMillions",
    imagesrc: "/logo/logo-megamillion.png",
    link: "https://www.megamillions.com/",
    drawtime: "11:00 PM",
    drawdate: "Tue & Fri",
    numberofballs: "5",
    min: "1",
    max: "70",
    repeating: false,
    hasball: true,
    ballmin: "1",
    ballmax: "25",
    cost: "$2",
    odds: "1 in 24.00",
  },
  powerball: {
    name: "Powerball",
    imagesrc: "/logo/logo-powerball.png",
    link: "https://www.powerball.com/games/home",
    drawtime: "10:59 PM",
    drawdate: "Mon, Wed & Sat",
    numberofballs: "5",
    min: "1",
    max: "69",
    repeating: false,
    hasball: true,
    ballmin: "1",
    ballmax: "26",
    cost: "$2",
    odds: "1 in 24.90",
  },
};

export const stategame = {
  ny: {
    cash4life: {
      name: "Cash4Life",
      imagesrc: "/logo/logo-cash4life.png",
      link: "https://nylottery.ny.gov/draw-game?game=cash4life",
      drawtime: "9:00 PM",
      drawdate: "Daily",
      numberofballs: "5",
      min: "1",
      max: "60",
      repeating: false,
      hasball: true,
      ballmin: "1",
      ballmax: "4",
      cost: "$2",
      odds: "1 in 7.76",
    },
    numbers: {
      name: "Numbers",
      imagesrc: "/logo/logo-numbers.png",
      link: "https://nylottery.ny.gov/draw-game?game=numbers",
      drawtime: "2:15 PM & 10:20 PM",
      drawdate: "Daily",
      numberofballs: "3",
      min: "0",
      max: "9",
      repeating: true,
      hasball: false,
      ballmin: "",
      ballmax: "",
      cost: "$0.50 or $1",
      odds: "",
    },
    pick10: {
      name: "Pick10",
      imagesrc: "/logo/logo-pick10.png",
      link: "https://nylottery.ny.gov/draw-game?game=pick10",
      drawtime: "8:30 PM",
      drawdate: "Daily",
      numberofballs: "10",
      min: "1",
      max: "80",
      repeating: false,
      hasball: false,
      ballmin: "",
      ballmax: "",
      cost: "$1",
      odds: "1 in 17.00",
    },
    take5: {
      name: "Take5",
      imagesrc: "/logo/logo-take5.png",
      link: "https://nylottery.ny.gov/draw-game?game=take5",
      drawtime: "2:15 PM & 10:20 PM",
      drawdate: "Daily",
      numberofballs: "5",
      min: "1",
      max: "39",
      repeating: false,
      hasball: false,
      ballmin: "",
      ballmax: "",
      cost: "$1",
      odds: "1 in 8.77",
    },
    win4: {
      name: "Win4",
      imagesrc: "/logo/logo-win4.png",
      link: "https://nylottery.ny.gov/draw-game?game=win4",
      drawtime: "2:15 PM & 10:20 PM",
      drawdate: "Daily",
      numberofballs: "4",
      min: "0",
      max: "9",
      repeating: true,
      hasball: false,
      ballmin: "",
      ballmax: "",
      cost: "$0.50 or $1",
      odds: "",
    },
    nylotto: {
      name: "NYLotto",
      imagesrc: "/logo/logo-nylotto.png",
      link: "https://nylottery.ny.gov/draw-game?game=lotto",
      drawtime: "8:15 PM",
      drawdate: "Wed & Sat",
      numberofballs: "6",
      min: "1",
      max: "59",
      hasball: false,
      ballmin: "",
      ballmax: "",
      cost: "$1",
      odds: "1 in 92.05",
    },
  },
  nj: {
    njlot: {
      name: "Temp",
      imagesrc: "/logo/logo-cash4life.png",
      link: "https://nylottery.ny.gov/draw-game?game=cash4life",
      drawtime: "5PM",
      drawdate: "3PM",
      numberofballs: "6",
      min: "1",
      max: "59",
      hasball: false,
      ballmin: "",
      ballmax: "",
      cost: "$1",
      odds: "1 in 92.05",
    },
  },
};
